### ISSUE TITLE
Old Cocoapod version

### ISSUE THREAD

**Issue by jamiedaniel** [yonat/MultiSelectSegmentedControl#28]
**Description of the problem:**
When using the cocoapods default entry. The base version offered is 1.2.1 which fails the tests etc.

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
- Create a new app.
- Git init the project.
- pod 'MultiSelectSegmentedControl' in the Podfile
- pod install
- check the version is 1.2.1 not the most current which should. e the default behavior.

**Comment by yonat** [comment]
Latest version is 2.1.1 . What tests fail?

**Comment by jamiedaniel** [comment]
When using cocoapods It doesn’t find version 2, it only uses version 1.
It fails when trying to specify the version.

**Comment by yonat** [comment]
It's hard to tell what's the problem without seeing your Podfile, you're Podfile.lock, and the errors you're getting...

You may try running `pod update MultiSelectSegmentedControl` and see if it helps.

**Comment by yonat** [comment]
@jamiedaniel Did it work? Still having problems? Have specific errors to share?

**Comment by vokal-isaac** [comment]
I think there are two issues right now.  For reasons that are not at all clear to me, the search feature on cocoapods.org shows the version number as 1.2.1:
<img width="1318" alt="Screen Shot 2019-10-22 at 10 44 11 AM" src="https://user-images.githubusercontent.com/7505072/67304365-52fdc280-f4b9-11e9-86c4-0eb43ae375d2.png">
I think this is at least related to the original issue here.

Second, it appears that 2.2.0 is the latest version pushed to pod trunk, despite a 2.3.0 release being tagged here on GitHub:
<img width="1322" alt="Screen Shot 2019-10-22 at 10 44 35 AM" src="https://user-images.githubusercontent.com/7505072/67304367-52fdc280-f4b9-11e9-919c-39ec9a351c7c.png">

**Comment by yonat** [comment]
The search results error on cocoapods.org is out of my control.

As for the difference between the latest git tag (2.3.0) and the latest pod trunk version (2.2.0), this is because of [this CocoaPods trunk push issue](https://github.com/CocoaPods/CocoaPods/issues/8915).  
In essence, it means a pod can either have SwiftUI option and iOS  >= 11, or no SwiftUI and iOS < 11. Version 2.3.0 adds an optional SwiftUI wrapper, and so can't be pushed to trunk unless I change the iOS version to 11 (which breaks some of my clients projects).
